config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users

  resources :posts do
    member do
      get 'like', to: 'posts#upvote'
      get 'dislike', to: 'posts#downvote'
    end
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true, counter_cache: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  # associations
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  #validation
  validates_presence_of :title, :content, :link

  # paperclip
  has_attached_file :image, styles:{ large: "600x600>",
                                    medium: "300x300>",
                                     small: "150x150#" },
   url: "/assets/:class/:id/:style.:extension",
   path: ":rails_root/public/assets/:class/:id/:style.:extension"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_attachment_presence :image
  validates_attachment_file_name :image, matches: [/png\Z/, /jpe?g/]
  validates_attachment_size :image, less_than: 3.megabytes

  # acts as votable
  acts_as_votable

  # friendly id
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]
  validates_presence_of :slug
  def should_generate_new_friendly_id?
   title_changed?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # associations
  has_many :posts
  has_many :comments, as: :commentable

  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_commentable

  def index
    @commentable = Post.friendly.find(params[:post_id])
    @comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    @user = current_user
    @comment = @commentable.comments.new(comments_params)
    @comments = @user.posts.to_a.collect{|v| v.comments.to_a }.flatten
    @comment.user_id = @user.id

    if @comment.save
      redirect_to @commentable, notice: 'Thank you for good comment!'
    else
      # redirect_to post_path(@post), notice: "You didn't write any comments!"
      redirect_to :new, notice: "You didn't write any comments!"
    end
  end

  # def destroy
  #   @commentable = Post.find(params[:post_id])
  #   @comment = @commentable.comments.find(params[:id])
  #   @comment.destroy
  #   redirect_to post_url
  # end

  private
  def comments_params
    params.require(:comment).permit(:body)
  end

  def load_commentable
    resource, id = request.path.split('/')[1,2] # /post/1
    @commentable = resource.singularize.classify.constantize.friendly.find(id) # Post.find(1)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :find_user, only: [:new, :create, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post_redirect, only: [:show]

  def index
    # @posts = Post.all.order("created_at DESC") #order based on creation date
    @posts = Post.all.order(cached_votes_up: :desc) #order based on numbers of votes up
    @posts = Post.paginate(:page => params[:page], :per_page => 1)
    @titles = Post.all
  end

  def show
    @commentable = @post
    @comments = @commentable.comments
    @comment = Comment.new
    @random_post = Post.friendly.where.not(id: @post).order("RANDOM()").first

  end

  def new
    @post = @user.posts.build
  end

  def create
    @post = @user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end


  def upvote
    @post.upvote_by @user
    flash[:notice] = "Thanks for voting #{@user.name}."
    redirect_to :back
  end

  def downvote
    @post.downvote_from @user
    flash[:notice] = "Thanks for voting #{@user.name}."
    redirect_to :back
  end

private
  def post_params
    params.require(:post).permit(:title, :content, :link, :image, :slug)
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  end

  def find_user
    @user = current_user
  end

  def set_post_redirect
    @post = Post.friendly.find(params[:id])
    # If an old id or a numeric id was used to find the record, then
    # the request path will not match the post_path, and we should do
    # a 301 redirect that uses the current friendly id.
    if request.path != post_path(@post)
      redirect_to @post, status: :moved_permanently
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.haml
- @comments.each do |comment|
  %p
    %strong Body:
    = comment.body
  %p
    %strong By:
    = comment.user.name
  %p
    %strong Published:
    = time_ago_in_words(comment.created_at)
    ago
  %hr
/- if current_user == comment.user
/%p= link_to "Remove Comment", [@commentable, comment], method: :delete, data: { confirm: "Are you sure you want to remove this comment?" }

app/views/comments/_form.html.haml
/simple_form_for([@post, @post.comments.build]) do |form|
/form.input :body, label: false
/form.button :submit

= simple_form_for [@commentable, @comment] do |f|
  = f.input :body,  as: :text, rows: 8
  = f.button :submit

app/views/comments/index.html.haml
%h2 Comments
= render 'comments'
%p= link_to "New", [:new, @commentable, :comment]

app/views/comments/new.html.haml
%h2 New Comments
= render 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Dribbble - #{yield :title}
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %p.notice= notice
    %p.alert= alert
    %nav
      = link_to "Home", root_path
    %hr/
    - if user_signed_in?
      Welcome,
      %strong
      = link_to current_user.name, edit_user_registration_path
      |
      = link_to 'Sign out', destroy_user_session_path
    - else
      = link_to 'Sign in', new_user_session_path
      = link_to 'Sign up', new_user_registration_path
    %hr/
    = yield


    %h2 Recent Posts
  %ul
    - @titles.each do |post|
      %li= link_to post.title, post

app/views/posts/_form.html.haml
= simple_form_for @post, html: { multipart: true } do |f|
  %p= f.input :image
  %p= f.input :title
  %p= f.input :link
  %p= f.input :content, as: :text
  %p= f.button :submit

app/views/posts/edit.html.haml
%h3 Edit Post

= render 'form'

app/views/posts/index.html.haml
= will_paginate @posts
%h3 All Posts
- @posts.each do |post|
  %p= link_to image_tag(post.image.url(:small)), post
  %h3= link_to post.title, post
  %p= post.content
  %p= link_to post.link, post.link
  %p= pluralize(post.comments.count, "Comment")
  %p= pluralize(post.get_likes.size, "Like")
  %hr/

%p=link_to "New Post", new_post_path

app/views/posts/new.html.haml
%h3 New Post
=render 'form'
%hr/
=link_to "Home", root_path

app/views/posts/show.html.haml
= content_for :title do
  = @post.title

%h2= @post.title
%p= image_tag @post.image.url(:medium)
%p= link_to @post.link, @post.link
%p= @post.content
%p= @post.get_likes.size
%p= @post.get_dislikes.size

- if user_signed_in?
  = link_to 'Dislike', dislike_post_path(@post), method: :get
  = link_to 'Like', like_post_path(@post), method: :get

%h2= pluralize(@post.comments.count, "Comment")
= render 'comments/comments'
%h3 Reply to thread
- if user_signed_in?
  = render "comments/form"
  %p
  =link_to "Edit Post", edit_post_path(@post)
  |
  =link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }

- else
  %p
    You need to
    = link_to "sign in", new_user_session_path
    before you comment!

%p Random Posts
%ul
  %li= link_to (image_tag @random_post.image.url(:medium)), post_path(@random_post)
  %li= @random_post.title
  %li= @random_post.user.name